// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBnPXZtPO8W0AfkeZ4E1HibfUF17Qq-yVU',
    appId: '1:572738572418:web:3671ae2132a4d3f35ce49b',
    messagingSenderId: '572738572418',
    projectId: 'vrittech-bacca',
    authDomain: 'vrittech-bacca.firebaseapp.com',
    storageBucket: 'vrittech-bacca.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCH9ycmuyHWJdpHe95se1emr3TF1WEJkvU',
    appId: '1:572738572418:android:162724806864e6715ce49b',
    messagingSenderId: '572738572418',
    projectId: 'vrittech-bacca',
    storageBucket: 'vrittech-bacca.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBLda_NB-VYq_e2j7qH6Jj65XMVZmPp68M',
    appId: '1:572738572418:ios:4d867c0eb74cada55ce49b',
    messagingSenderId: '572738572418',
    projectId: 'vrittech-bacca',
    storageBucket: 'vrittech-bacca.appspot.com',
    iosBundleId: 'com.example.vrititech',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBLda_NB-VYq_e2j7qH6Jj65XMVZmPp68M',
    appId: '1:572738572418:ios:4d867c0eb74cada55ce49b',
    messagingSenderId: '572738572418',
    projectId: 'vrittech-bacca',
    storageBucket: 'vrittech-bacca.appspot.com',
    iosBundleId: 'com.example.vrititech',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBnPXZtPO8W0AfkeZ4E1HibfUF17Qq-yVU',
    appId: '1:572738572418:web:9868db082366e4dd5ce49b',
    messagingSenderId: '572738572418',
    projectId: 'vrittech-bacca',
    authDomain: 'vrittech-bacca.firebaseapp.com',
    storageBucket: 'vrittech-bacca.appspot.com',
  );
}
